Models/Album.cs
using System.ComponentModel.DataAnnotations;

namespace HoliPics.Models
{
    public class Album
    {
        public int Id { get; set; }

        public string? CreatorId { get; set; }

        public List<string>? Owners { get; set; }

        [Display(Name = "Created by")]
        public string? CreatedBy { get; set; }

        [Display(Name = "Time of creation")]
        public DateTime CreationTime { get; set; }

        public DateTime LastUpdated { get; set; }

        [DataType(DataType.Text)]
        public string Name { get; set; }

        [DataType(DataType.Text)]
        public string? Description { get; set; }

        public List<string>? Diary { get; set; }

        public List<string> Images { get; set; }  
        
        public int UploadProgress { get; set; }

        public string? Thumbnail { get; set; }
        
        
        public Album()
        {                  
            Images = new List<string>();
            UploadProgress = 0;
        }

        public int? ImageCount()
        { return Images.Count; }

    }
}

Controllers/AlbumController.cs
using HoliPics.Authorization;
using HoliPics.Data;
using HoliPics.Models;
using HoliPics.VievModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using HoliPics.Services.Interfaces;
using Microsoft.AspNetCore.Identity;
using HoliPics.Areas.Identity.Data;
using MetadataExtractor;
using MetadataExtractor.Formats.Exif;
using System.Globalization;
using System.Collections.Generic;
using Microsoft.IdentityModel.Tokens;


namespace HoliPics.Controllers
{
    public class AlbumController : SuperController
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly Dictionary<string, int> _imageSizes;
        private readonly IImageService _imageService;   
        private readonly UserManager<HoliPicsUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<AlbumController> _logger;

        public AlbumController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IAuthorizationService authorizationService, IImageService imageService, UserManager<HoliPicsUser> userManager, RoleManager<IdentityRole> roleManager, ILogger<AlbumController> logger)
            : base(context, webHostEnvironment, authorizationService, imageService, userManager, roleManager, logger)
        {
            _context = context;
            _authorizationService = authorizationService;
            _webHostEnvironment = webHostEnvironment;
            _imageSizes = new Dictionary<string, int>()
            {
                { "Large_", 1300 },
                { "Medium_",  420 },
                { "Small_", 205 }
            };
            _imageService = imageService;
            _userManager = userManager;
            _roleManager = roleManager;
            _logger = logger;
        }


        // GET: Album
        [Authorize]        
        public async Task<IActionResult> Index(int id)
        {            
            var album = await _context.Albums.FindAsync(id);
            var permissionResult = await CheckPermission(album, AlbumOperations.Read);
            if (permissionResult is not OkResult) { return permissionResult; }
            ViewData["ImagesSortedByDate"] = await GetImgSortByDate(album.Images);
            ViewData["DiaryDict"] = GetDiarySortByDate(album.Diary);
            return View(album);
        }

        private async Task<SortedDictionary<DateTime, List<string>>> GetImgSortByDate(List<string> fileNames)
        {
            SortedDictionary <DateTime, List<string>> sortedByDate = new SortedDictionary<DateTime, List<string>>();
            foreach (var fileName in fileNames)
            {
                var image = await _context.Images.FirstOrDefaultAsync(im => im.FileName == fileName);
                if (image == null) { continue; }
                // Add new (Key, Value) pair if key does not exist.
                if (!sortedByDate.TryGetValue(image.DateTaken.Date, out List<string>? imageNames))
                {
                    imageNames = new List<string>();
                    sortedByDate.Add(image.DateTaken.Date, imageNames);
                }
                imageNames.Add(fileName);
            }            
            return sortedByDate;
        }

        private SortedDictionary<DateTime, string> GetDiarySortByDate(List<string>? diaryString)
        {
            SortedDictionary<DateTime, string> diary = new SortedDictionary<DateTime, string>();
            if (diaryString != null)
            {
                foreach (string entry in diaryString)
                {
                    var splitted = entry.Split('|');
                    if (splitted.Length > 0)
                    {
                        DateTime date;
                        bool parsedSucces = DateTime.TryParse(splitted[0], CultureInfo.CurrentCulture,
                        DateTimeStyles.None, out date);
                        if (parsedSucces) { diary.Add(date, String.Join("|", splitted.Skip(1))); }
                    }
                }
            }            
            return diary;
        }

        public IActionResult Upload(int id)
        {   
            var imageView = new ImageViewModel { AlbumId = id };
            return View(imageView);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(ImageViewModel images, int id)
        {
            var album = await _context.Albums.FindAsync(id);
            var permissionResult = await CheckPermission(album, AlbumOperations.Create);
            if (permissionResult is not OkResult) { return permissionResult; }

            var imageView = new ImageViewModel { AlbumId = id };            
                      
            if (ModelState.IsValid)
            {                                
                long totalBytes = images.ImageFiles.Sum(f => f.Length);
                long totalReadBytes = 0;

                List<Img> imgs = new List<Img>();
                if (images.ImageFiles != null)
                {
                    foreach (var file in images.ImageFiles)
                    {
                        // Assign a unique identifier to the filename
                        var fileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);

                        Img imageFile = new Img { AlbumId = id, DateTaken = GetDateTime(file.OpenReadStream()), FileName = fileName };
                        imgs.Add(imageFile);                       

                        // Record the upload progress
                        byte[] buffer = new byte[16 * 1024];
                        using (Stream stream = file.OpenReadStream())
                        {
                            int readBytes;
                            while ((readBytes = stream.Read(buffer, 0, buffer.Length)) > 0)
                            {
                                totalReadBytes += readBytes;
                                album.UploadProgress = (int)((float)totalReadBytes / (float)totalBytes * 100.0);
                                await _context.SaveChangesAsync();                                
                            }
                        }

                        // Store image in different sizes
                        foreach (KeyValuePair<string, int> size in _imageSizes)
                        {                          
                            using Image image = Image.Load(file.OpenReadStream()); 
                            image.Mutate(x => x.Resize(size.Value, 0));
                            
                            // Store the uploaded file in the cloud                            
                            using MemoryStream mutatedImageStream = new MemoryStream();                            
                            image.Save(mutatedImageStream, Image.DetectFormat(file.OpenReadStream()));
                            _imageService.UploadImageToBlob(mutatedImageStream, size.Key + fileName);
                        }
                    }
                }
                album.UploadProgress = 0;
                foreach (var imageFile in imgs)
                {       
                    // Add the image filename to the album
                    album.Images.Add(imageFile.FileName);                       

                    // Track the changes to imagefile and album
                    _context.Add(imageFile);
                }
                if (album.Thumbnail == "placeholder.png")
                {
                    album.Thumbnail = "Medium_" + album.Images[0];
                }
                album.LastUpdated = DateTime.Now;

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { id });                              
            }
            return View(imageView);
        }

        // Get the progress of image uploading
        [HttpGet]
        public async Task<ActionResult> Progress(int id)
        {
            var album = await _context.Albums.FindAsync(id);
            return this.Content(album.UploadProgress.ToString());
        }

        [Authorize]
        public async Task<ActionResult> GetImage(string filename)
        {
            (Stream imageStream, string contentType) = await _imageService.GetImageFromBlob(filename);

            return File(imageStream, contentType);
        }     


        [Authorize]
        public async Task<IActionResult> Picture(string id) // id = FileName
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Images.FirstOrDefaultAsync(im => im.FileName == id);

            var album = await _context.Albums
                .FirstOrDefaultAsync(m => m.Id == image.AlbumId);
            if (album == null)
            {
                return NotFound();
            }
            var permissionResult = await CheckPermission(album, AlbumOperations.Read);
            if (permissionResult is not OkResult) { return permissionResult; }
          
            return View(image);
        }


        [HttpPost]
        [Authorize]        
        public async Task<IActionResult> SetThumbnail(int id)
        {        
            var image = await _context.Images.FirstOrDefaultAsync(im => im.Id == id);
            var album = await _context.Albums.FindAsync(image.AlbumId);
            var permissionResult = await CheckPermission(album, AlbumOperations.Update);
            if (permissionResult is not OkResult) { return permissionResult; }

            if (image != null)
            {
                album.Thumbnail = "Medium_" + image.FileName;

Views/Album/DefaultDisplayPartial.cshtml
@model HoliPics.Models.Album


@{
    int i = 0;
    var sortedByDateDict = (SortedDictionary<DateTime, List<string>>?)ViewData["ImagesSortedByDate"];

    if (sortedByDateDict != null)
    {
        foreach (KeyValuePair<DateTime, List<string>> sortedByDate in sortedByDateDict)
        {                
            <div class="row mt-4">
                @if (sortedByDate.Key.Equals(new DateTime()))
                {
                    <p>Unknown date</p>
                }
                else
                {
                    <p>@sortedByDate.Key.Date.ToString("D")</p>
                }
            </div>

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-3 g-2">                    
                @foreach (string item in sortedByDate.Value)
                {
                    string imgName = $"Medium_{item}";
                    if (i < 7)
                    {
                        <div class="col">
                            <a asp-action="Picture" asp-route-id="@item">
                                <img src="/album/GetImage?filename=@imgName" class="w-100 shadow-1-strong rounded mb-0" asp-append-version="true" />
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="col">
                            <a asp-action="Picture" asp-route-id="@item">
                                <img src="/album/GetImage?filename=@imgName" class="w-100 shadow-1-strong rounded mb-0" loading="lazy" asp-append-version="true" />
                            </a>
                        </div>
                    }
                    i++;
                } 
            </div>   
        }
    }        
}

Views/Album/FocusDisplayPartial.cshtml
@model HoliPics.Models.Album

@if (Model.Images.Count > 0)
{
    <div id="carouselExample" class="carousel slide carousel-fade">
        <div class="carousel-inner">
            @{string firstImg = $"Large_{Model.Images[0]}";}
            <div class="carousel-item active text-center">
                <img src="/album/GetImage?filename=@firstImg" class="closeup" asp-append-version="true" />
            </div>
            @foreach (var item in Model.Images)
            {   @if (item != Model.Images[0])
                {
                    string imgName = $"Large_{item}";
                    <div class="carousel-item text-center">
                        <img src="/album/GetImage?filename=@imgName" class="closeup" loading="lazy" asp-append-version="true" />
                    </div>
                }

            }
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
}

Views/Album/InfoDisplayPartial.cshtml
@model HoliPics.Models.Album


@{
    var sortedByDateDict = (SortedDictionary<DateTime, List<string>>?)ViewData["ImagesSortedByDate"];

    if (sortedByDateDict != null)
    {
        foreach (KeyValuePair<DateTime, List<string>> sortedByDate in sortedByDateDict)
        {
            <div class="row mt-4">
                @if (sortedByDate.Key.Equals(new DateTime()))
                {
                    <p>Unknown date</p>
                }
                else
                {
                    <p>@sortedByDate.Key.Date.ToString("D")</p>
                }
            </div>

            <div class="row row-cols-3 row-cols-sm-4 row-cols-md-5 row-cols-lg-6 g-2">
                @foreach (string item in sortedByDate.Value)
                {
                    string imgName = $"Small_{item}";
                    <div class="col">
                        <a asp-action="Picture" asp-route-id="@item">
                            <img src="/album/GetImage?filename=@imgName" class="w-100 shadow-1-strong rounded mb-0" loading="lazy" asp-append-version="true" />
                        </a>
                    </div>
                }
            </div>
        }
    }
}

Views/Album/Picture.cshtml
@model HoliPics.Models.Img

@{
    ViewData["Title"] = "Picture";
}

<style>
    body {
        background-color:black;
    }
</style>

<nav class="navbar navbar-expand navbar-dark bg-transparent full-bleed ignore-padding-top">
    <div class="container-fluid">
        <div class="navbar">
            <a asp-area="" asp-action="Index" asp-controller="Album" asp-route-id="@Model.AlbumId" class="btn btn-dark rounded-circle" type="button">
                <i class="bi bi-arrow-left-short h3"></i>
            </a>
        </div>
        <div class="navbar justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    
                    <button type="button" class="btn btn-link text-white rounded-circle" id="liveAlertBtn" onclick="setPlaceholder()" data-bs-toggle="tooltip"
                    data-bs-title="Set as thumbnail" data-bs-placement="bottom">
                        <i class="bi bi-card-image h4"></i>
                    </button>
                </li>
                <li class="nav-item">
                    <button type="button" class="btn btn-link text-white rounded-circle" data-bs-toggle="modal" data-bs-target="#deleteImage">
                        <i class="bi bi-trash h4"></i>
                    </button>
                </li>              
            </ul>            
        </div>
    </div>
</nav>

<div id="liveAlertPlaceholder"></div>


@{
    string imgName = $"Large_{Model.FileName}";    
}
<div class="text-center">
    <img src="/album/GetImage?filename=@imgName" class="closeup" />
</div>


<div class="modal fade" id="deleteImage" tabindex="-1" aria-labelledby="deleteImageLabel">
    <div class="modal-dialog text-dark">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="deleteImageTitel">Delete Picture</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h4>Are you sure you want to delete this picture?</h4>
                <p>This action cannot be undone.</p>
            </div>
            <div class="modal-footer">
                <form asp-action="Delete-Image">
                    <input type="hidden" asp-for="@Model.Id" />
                    <input type="submit" value="Delete" class="btn btn-danger" /> |
                </form>
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">

        function setPlaceholder() {
            $.post(
                "/Album/SetThumbnail/" + @Model.Id
                        );
        }

        const alertPlaceholder = document.getElementById('liveAlertPlaceholder')
        const appendAlert = (message, type) => {
            const wrapper = document.createElement('div')
            wrapper.innerHTML = [
                `<div class="alert alert-${type} alert-dismissible" role="alert">`,
                `   <div>${message}</div>`,
                '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                '</div>'
            ].join('')

            alertPlaceholder.append(wrapper)
        }

        const alertTrigger = document.getElementById('liveAlertBtn')
        if (alertTrigger) {
            alertTrigger.addEventListener('click', () => {
                appendAlert('<i class="bi bi-check-circle-fill"></i> Thumbnail updated!', 'success')
            })

        }
    </script>

    <script type="text/javascript">
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
}

Views/Album/Upload.cshtml
@model HoliPics.VievModels.ImageViewModel
@{
    ViewData["Title"] = "Upload";
}

<div class ="text-center">
    <h1 class="display-4">Upload picture to album</h1>
    <p>Accepted formats are .gif, .jpg and .png.</p>
    <form method="post" enctype="multipart/form-data" asp-action="Upload" id="uploadForm">
        <div class="custom-file mb-4">
            <input asp-for="ImageFiles" class="custom-file-input" id="customFile" accept=".gif, .jpg, .png" multiple>            
            <label class="custom-file-label button" for="customFile">Choose picture</label>
        </div>
        <span asp-validation-for="ImageFiles" class="text-danger"></span>
        <div class="form-group">
            <input asp-route-id="@Model.AlbumId" type="submit" value="submit" onclick="startUpdatingProgressIndicator()" class="btn btn-sm btn-primary rounded-0 text-uppercase" />
            <a asp-action="Index" asp-route-id="@Model.AlbumId" class="btn btn-sm btn-primary rounded-0 text-uppercase"><i class="fas fa-fast-backward"></i> Back to album</a>
        </div>
    </form>
</div>


<div class="progress" id="progressBar">
    <div id="progress" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
        <div id="label" class="control-label">0%</div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" charset="utf-8">
        var intervalId;
        $("#progressBar").hide();

        function startUpdatingProgressIndicator() {
            $("#progressBar").show();
            $("#progress").show();
            $("#uploadForm").hide();
            intervalId = setInterval(
                function () {
                    $.get(
                        "/Album/progress/" + @Model.AlbumId,
                        function (progress) {                            
                            $("#progress").css({ width: progress + "%" });
                            $("#label").html(progress + "%");
                        }
                    );
                },
                10
            );
        }
    </script>
}